name: test workflow

on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: https://discord.com/api/webhooks/1194525313250631690/5plhcYAU6BqpofXUZTFi_WXoPeOAlkmM5b-KilBCgbnbdn-TO1DSANQQgYYw1HLaVW6X
          status: ${{ job.status }}
          title: "build"
          description: "Succeeded build workflow"
          color: 0x0000ff
          username: GitHub Actions